version: "3"

volumes:
  db-data:

services:
  
  server:
    image: todo-fastapi:latest
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      FASTAPI_PORT: 3000
      FASTAPI_RELOAD: True
      FASTAPI_HOST: 0.0.0.0
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test123
      POSTGRES_SERVER: 0.0.0.0
      POSTGRES_PORT: 5432
      POSTGRES_DB: todo-db

  db:
    restart: always
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test123
      POSTGRES_DB: postgres